name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true  # Установит зависимости, если есть файл
          pip install flake8 pytest pytest-cov  # Добавлен pytest вместо nose

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with pytest
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)  # Добавляем текущую директорию в PYTHONPATH
          pytest --cov=app  # Покрытие кода тестами  
